apiVersion: v1
kind: Service
metadata:
  name: examplesearch
  namespace: default
  labels:
    app: examplesearch
spec:
  selector:
    app: examplesearch
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
