apiVersion: apps/v1
kind: Deployment
metadata:
  name: examplesearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examplesearch
      version: 'v1'
  template:
    metadata:
      labels:
        app: examplesearch
        version: 'v1'
    spec:
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              while true
              do
                rt=$(nc -z -w 1 examplesearch-mysql 3306)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: examplesearch-app
          image: 02645/examplesearch
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://examplesearch-mysql.default.svc.cluster.local:3306/examplesearch?useUnicode=true&characterEncoding=utf8&useSSL=false
            - name: SPRING_DATA_JEST_URI
              value: http://examplesearch-elasticsearch.default.svc.cluster.local:9200
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: http://examplesearch-elasticsearch.default.svc.cluster.local:9200
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 120
